SELECT 
	ORDERID,
	ORDERDATE,
	SHIPDATE,
	SHIPMODE,
	CUSTOMERID,
	PRODUCTID,
	ORDERCOSTPRICE,
	ORDERSELLINGPRICE,
    (ORDERSELLINGPRICE - ORDERCOSTPRICE) AS ORDERPROFIT
FROM
	{{ ref( 'raw_orders' )}}