SELECT 
	ORDERID,
	ORDERDATE,
	SHIPDATE,
	SHIPMODE,
    ORDERCOSTPRICE,
    ORDERSELLINGPRICE,
    (ORDERSELLINGPRICE - ORDERCOSTPRICE) AS ORDERPROFIT,
    c.CUSTOMERNAME AS CUSTOMERNAME,
    c.SEGMENT AS SEGMENT,
    c.COUNTRY AS COUNTRY,
    p.CATEGORY AS CATEGORY,
    PRODUCTNAME,
	SUBCATEGORY
FROM
	{{ ref( 'raw_orders' )}} o
LEFT JOIN {{ ref( 'raw_customer' )}} c 
on o.CUSTOMERID = c.CUSTOMERID
LEFT JOIN {{ ref( 'raw_products' )}} p
on o.PRODUCTID = p.PRODUCTID